[package]
name = "rhfiles-core"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62", features = [
    "Win32_Foundation",
    "Win32_Storage_FileSystem",
    "Win32_UI_Shell",
    "Win32_System_Com",
    "Win32_System_Registry",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging",
    "Win32_System_Ole",
    "Win32_Graphics_Gdi",
] }

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.serde_json]
version = "1"

[build-dependencies]
cc = "1"

[dependencies.toml]
version = "0.8"

[dependencies.image]
version = "0.25"

[dependencies.rayon]
version = "1"

[dependencies.base64]
version = "0.22"

[dependencies.notify]
version = "7"
optional = true

[dependencies.chrono]
version = "0.4"

[dependencies.md-5]
version = "0.10"

[dependencies.sha1]
version = "0.10"

[dependencies.sha2]
version = "0.10"

[dependencies.digest]
version = "0.10"
