# Restores the hand-maintained Android inputs that `cargo tauri android init`
# regenerates from a template, and guarantees a signing key exists.
#
#   pwsh -File scripts/android-sync.ps1
#
# Run this after `cargo tauri android init`, and before any build (it is cheap and
# idempotent). It:
#   1. creates the shared signing keystore on first use,
#   2. writes keystore.properties into the generated Gradle project,
#   3. restores android/gradle/app/build.gradle.kts (one signing key for both
#      debug and release, so an update never needs an uninstall),
#   4. restores android/manifest/AndroidManifest.xml (permissions).

param(
    [string]$Keystore
)

$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
$generatedRoot = Join-Path $repoRoot 'android\src-tauri\gen\android'

if (-not (Test-Path $generatedRoot)) {
    throw "the Android project has not been generated yet. Run 'cargo tauri android init' in android/ first."
}

# --- 1. signing key ---------------------------------------------------------

$javaHome = @(
    $env:JAVA_HOME,
    'C:\Program Files\Microsoft\jdk-21.0.12.101-hotspot'
) | Where-Object { $_ -and (Test-Path (Join-Path $_ 'bin\keytool.exe')) } | Select-Object -First 1
if (-not $javaHome) {
    throw 'no JDK with keytool found; set JAVA_HOME to a JDK 17+ installation'
}
$env:JAVA_HOME = $javaHome

if (-not $Keystore) {
    $Keystore = Join-Path $env:USERPROFILE '.android\rhfiles-debug.keystore'
}
if (-not (Test-Path $Keystore)) {
    Write-Host "creating shared signing keystore: $Keystore"
    New-Item -ItemType Directory -Force -Path (Split-Path -Parent $Keystore) | Out-Null
    & (Join-Path $javaHome 'bin\keytool.exe') -genkeypair -v -keystore $Keystore `
        -storepass android -keypass android -alias rhfiles -keyalg RSA -keysize 2048 `
        -validity 10000 -dname 'CN=RHFiles Debug,O=RHFiles,C=CN' | Out-Null
} else {
    Write-Host "using signing keystore: $Keystore"
}

# --- 2. keystore.properties -------------------------------------------------

$propertiesPath = Join-Path $generatedRoot 'keystore.properties'
$properties = @(
    "# Generated by scripts/android-sync.ps1 — do not edit the generated copy.",
    "storeFile=$($Keystore -replace '\\', '/')",
    'storePassword=android',
    'keyAlias=rhfiles',
    'keyPassword=android'
) -join "`n"
if ((Test-Path $propertiesPath) -and ((Get-Content $propertiesPath -Raw).Trim() -eq $properties.Trim())) {
    Write-Host "already in sync: $propertiesPath"
} else {
    Set-Content -Path $propertiesPath -Value $properties -NoNewline
    Write-Host "updated: $propertiesPath"
}

# --- 3. and 4. files that the template gets wrong or must not own -----------

function Sync-File {
    param([string]$Source, [string]$Target)

    if (-not (Test-Path $Source)) { throw "missing source file: $Source" }
    if (-not (Test-Path (Split-Path -Parent $Target))) {
        throw "missing target directory: $(Split-Path -Parent $Target)"
    }

    $desired = (Get-Content $Source -Raw)
    if ((Test-Path $Target) -and ((Get-Content $Target -Raw) -eq $desired)) {
        Write-Host "already in sync: $Target"
        return
    }
    Copy-Item $Source $Target -Force
    Write-Host "updated: $Target"
}

$appDir = Join-Path $generatedRoot 'app'
Sync-File `
    -Source (Join-Path $repoRoot 'android\gradle\app\proguard-rules.pro') `
    -Target (Join-Path $appDir 'proguard-rules.pro')
Sync-File `
    -Source (Join-Path $repoRoot 'android\gradle\app\build.gradle.kts') `
    -Target (Join-Path $appDir 'build.gradle.kts')

# Restore the origin-restricted Android integration and file-sharing roots.
Sync-File `
    -Source (Join-Path $repoRoot 'android\manifest\file_paths.xml') `
    -Target (Join-Path $appDir 'src\main\res\xml\file_paths.xml')

Sync-File `
    -Source (Join-Path $repoRoot 'android\gradle\app\src\main\java\com\railgunhamster\rhfiles\MainActivity.kt') `
    -Target (Join-Path $appDir 'src\main\java\com\railgunhamster\rhfiles\MainActivity.kt')

# New native modules and JVM business tests are canonical inputs too.
foreach ($sourceSet in @('main', 'test')) {
    $canonical = Join-Path $repoRoot "android\gradle\app\src\$sourceSet\java\com\railgunhamster\rhfiles"
    $destination = Join-Path $appDir "src\$sourceSet\java\com\railgunhamster\rhfiles"
    if (Test-Path $canonical) {
        New-Item -ItemType Directory -Force -Path $destination | Out-Null
        foreach ($source in Get-ChildItem -LiteralPath $canonical -File -Filter '*.kt') {
            Sync-File -Source $source.FullName -Target (Join-Path $destination $source.Name)
        }
    }
}

$targets = Get-ChildItem $generatedRoot -Recurse -File -Filter 'AndroidManifest.xml' |
    Where-Object { $_.FullName -notlike '*\build\*' }
if (-not $targets) {
    throw "no AndroidManifest.xml found under $generatedRoot"
}
foreach ($target in $targets) {
    Sync-File `
        -Source (Join-Path $repoRoot 'android\manifest\AndroidManifest.xml') `
        -Target $target.FullName
}

Write-Host 'Android project sync complete.'
